/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-24 01:04:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.dao.UserDao;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.dao.UserDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<title>header</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;700&family=Noto+Sans:wght@400;700&display=swap\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/header.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 아이콘.. -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/7027f21a5f.js\"\r\n");
      out.write("   crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");

request.setCharacterEncoding("utf-8");

String loginok = (String) session.getAttribute("loginok");
String myid = (String) session.getAttribute("myid");
String saveid = (String) session.getAttribute("saveid");
String saveok = "";
if (saveid != null) {
   saveok = (String) session.getAttribute("saveok");
}

UserDao dao = new UserDao();
String nickname = dao.getName_id(myid);
String user_num = dao.getNum(myid);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(function() {\r\n");
      out.write("\r\n");
      out.write("      $(\"#myBtn\").click(function() {\r\n");
      out.write("         $(\"#myModal\").modal();\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      $(\"#myBtn2\").click(function() {\r\n");
      out.write("         $(\"#myModal2\").modal();\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //로그인처리\r\n");
      out.write("      var loginform = document.getElementById('loginfrm');\r\n");
      out.write("\r\n");
      out.write("      loginform.addEventListener('submit', function(event) {\r\n");
      out.write("         event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("         var logindata = $(\"#loginfrm\").serialize();\r\n");
      out.write("\r\n");
      out.write("         $.ajax({\r\n");
      out.write("\r\n");
      out.write("            type : \"get\",\r\n");
      out.write("            dataType : \"json\",\r\n");
      out.write("            url : \"login/loginaction.jsp\",\r\n");
      out.write("            data : logindata,\r\n");
      out.write("            success : function(res) {\r\n");
      out.write("\r\n");
      out.write("               if (res.b) {\r\n");
      out.write("\r\n");
      out.write("                  location.reload();\r\n");
      out.write("               } else {\r\n");
      out.write("\r\n");
      out.write("                  alert(\"아이디와 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\r\n");
      out.write("               }\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //회원가입처리\r\n");
      out.write("      var gaipform = document.getElementById('gaipfrm');\r\n");
      out.write("\r\n");
      out.write("      gaipform.addEventListener('submit', function(event) {\r\n");
      out.write("         event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("         var gaipdata = $(\"#gaipfrm\").serialize();\r\n");
      out.write("         //alert(gaipdata);\r\n");
      out.write("         var result = $(\"#check_result\").text();\r\n");
      out.write("\r\n");
      out.write("         var a = result == \"사용가능한 아이디입니다😊\";\r\n");
      out.write("         if (a) {\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("\r\n");
      out.write("               type : \"get\",\r\n");
      out.write("               dataType : \"html\",\r\n");
      out.write("               url : \"user/user_addaction.jsp\",\r\n");
      out.write("               data : gaipdata,\r\n");
      out.write("               success : function() {\r\n");
      out.write("\r\n");
      out.write("                  alert(\"🎉회원가입을 축하합니다🎉\");\r\n");
      out.write("                  location.reload();\r\n");
      out.write("                  //$(\"#myModal\").modal();\r\n");
      out.write("\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("         } else {\r\n");
      out.write("\r\n");
      out.write("            alert(\"중복확인을 해주세요\");\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //idsearch 불러오기\r\n");
      out.write("      $(\"#search_id\")\r\n");
      out.write("            .keyup(\r\n");
      out.write("                  function(event) {\r\n");
      out.write("\r\n");
      out.write("                     if (event.which === 13) {\r\n");
      out.write("\r\n");
      out.write("                        var search = $(this).val();\r\n");
      out.write("                        //alert(search);\r\n");
      out.write("\r\n");
      out.write("                        location.href = \"index.jsp?main=movie/movie_search.jsp?search=\"\r\n");
      out.write("                              + search + \"&currentPage=1\";\r\n");
      out.write("                     }\r\n");
      out.write("                     ;\r\n");
      out.write("                  });\r\n");
      out.write("\r\n");
      out.write("      //엔터로 로그인\r\n");
      out.write("      $(\"#user_pw\").keyup(function(event) {\r\n");
      out.write("\r\n");
      out.write("         if (event.which === 13) {\r\n");
      out.write("\r\n");
      out.write("            var logindata = $(\"#loginfrm\").serialize();\r\n");
      out.write("            //alert(logindata);\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("\r\n");
      out.write("               type : \"get\",\r\n");
      out.write("               dataType : \"html\",\r\n");
      out.write("               url : \"login/loginaction.jsp\",\r\n");
      out.write("               data : logindata,\r\n");
      out.write("               success : function() {\r\n");
      out.write("\r\n");
      out.write("                  location.reload();\r\n");
      out.write("\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("         }\r\n");
      out.write("         ;\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //중복 아이디 체크\r\n");
      out.write("      $(\"#id_check\").click(function() {\r\n");
      out.write("\r\n");
      out.write("         var user_id = $(\"#user_id\").val();//user_id에 입력되는 값\r\n");
      out.write("\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url : \"user/idsearch.jsp\",\r\n");
      out.write("            type : \"get\",\r\n");
      out.write("            data : {\r\n");
      out.write("               \"user_id\" : user_id\r\n");
      out.write("            },\r\n");
      out.write("            dataType : 'json',\r\n");
      out.write("            success : function(res) {\r\n");
      out.write("               if (res.count == 1) {\r\n");
      out.write("                  $(\"#check_result\").html('중복된 아이디입니다.');\r\n");
      out.write("                  $('#check_result').css({\r\n");
      out.write("                     \"color\" : \"red\"\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#user_id\").val(\"\");\r\n");
      out.write("                  $(\"#user_id\").focus();\r\n");
      out.write("\r\n");
      out.write("               } else {\r\n");
      out.write("                  $(\"#check_result\").html('사용가능한 아이디입니다😊');\r\n");
      out.write("                  $('#check_result').css({\r\n");
      out.write("                     \"color\" : \"green\"\r\n");
      out.write("                  });\r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //회원가입 시 비번 일치\r\n");
      out.write("      $(\"#user_pw2\").focusout(function() {\r\n");
      out.write("\r\n");
      out.write("         var pw1 = $(\"#user_pw1\").val();\r\n");
      out.write("         var pw2 = $(\"#user_pw2\").val();\r\n");
      out.write("\r\n");
      out.write("         if (pw1 == pw2) {\r\n");
      out.write("            $(\"#pw_check\").html('비밀번호가 일치합니다.');\r\n");
      out.write("            $('#pw_check').css({\r\n");
      out.write("               \"color\" : \"green\"\r\n");
      out.write("            });\r\n");
      out.write("         } else {\r\n");
      out.write("            $(\"#pw_check\").html('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("            $('#pw_check').css({\r\n");
      out.write("               \"color\" : \"red\"\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#user_pw2\").val(\"\");\r\n");
      out.write("            $(\"#user_pw2\").focus();\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //아이디 저장\r\n");
      out.write("      $(\"#saveid\").click(function() {\r\n");
      out.write("\r\n");
      out.write("         var saveid = $(\"#saveid\").val();\r\n");
      out.write("         //alert(saveid);\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <header>\r\n");
      out.write("      <div class=\"top\">\r\n");
      out.write("\r\n");
      out.write("         <div class=\"logo\">\r\n");
      out.write("            <a href=\"index.jsp?main=layout/main.jsp\"><img\r\n");
      out.write("               src=\"layout_image/logo.png\"></a>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <nav class=\"menu\">\r\n");
      out.write("            <ul class=\"navi\">\r\n");
      out.write("               <li><a\r\n");
      out.write("                  href=\"index.jsp?main=movie/movie_list.jsp?movie_genre=all&sort=recent&currentPage=1\"\r\n");
      out.write("                  class=\"mainmenu\">영화</a></li>\r\n");
      out.write("               <li><a href=\"index.jsp?main=commu/commu_totallist.jsp\"\r\n");
      out.write("                  class=\"mainmenu\">커뮤니티</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </nav>\r\n");
      out.write("\r\n");
      out.write("         <form method=\"post\">\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\" id=\"search_id\" placeholder=\"검색\"\r\n");
      out.write("               class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("         </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <!-- 회원(로그인)모드.. -->\r\n");
      out.write("            ");

            if (loginok != null) {

               if (myid.equals("admin")) {
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"menu2\" style=\"  position: relative;\">\r\n");
      out.write("               <b\r\n");
      out.write("                  style=\"font-size: 10pt; font-weight: normal; margin-right: 10px;\">");
      out.print(nickname);
      out.write("님\r\n");
      out.write("                  로그인중 </b>\r\n");
      out.write("               <button type=\"button\" class=\"btn btn-default btn-sm\"\r\n");
      out.write("                  style=\"width: 80px; margin-right: 10px; \"\r\n");
      out.write("                  onclick=\"location.href='login/logoutaction.jsp'\">Logout</button>\r\n");
      out.write("               <div class=\"fa-solid fa-user-gear\"\r\n");
      out.write("                   style=\"font-size: 20px; height:30px; line-height:30px;\"\r\n");
      out.write("                  onclick=\"location.href='index.jsp?main=mypage/admin_mypage_form.jsp?user_num=");
      out.print(user_num);
      out.write("'\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            } else {
            
      out.write("\r\n");
      out.write("            <div class=\"menu2\">\r\n");
      out.write("               <b\r\n");
      out.write("                  style=\"font-size: 10pt; font-weight: normal; margin-right: 10px;\">");
      out.print(nickname);
      out.write("님\r\n");
      out.write("                  로그인중</b>\r\n");
      out.write("               <button type=\"button\" class=\"btn btn-default btn-sm\"\r\n");
      out.write("                  style=\"width: 80px; margin-right: 10px;\"\r\n");
      out.write("                  onclick=\"location.href='login/logoutaction.jsp'\">Logout</button>\r\n");
      out.write("               <div class=\"fa-solid fa-user\"\r\n");
      out.write("                  style=\"font-size: 20px; height:30px; line-height:30px;\"\r\n");
      out.write("                  onclick=\"location.href='index.jsp?main=mypage/mypage_form.jsp?user_num=");
      out.print(user_num);
      out.write("'\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            }
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");

            } else {
            
      out.write("\r\n");
      out.write("            <div class=\"menu2\">\r\n");
      out.write("               <button type=\"button\" class=\"btn btn-default btn-sm\" id=\"myBtn\"\r\n");
      out.write("                  data-toggle=\"modal\" data-target=\"#myModal\">로그인</button>\r\n");
      out.write("               <button type=\"button\" class=\"btn btn-default btn-sm\"\r\n");
      out.write("                  style=\"width: 100px;\" id=\"myBtn2\" data-toggle=\"modal\"\r\n");
      out.write("                  data-target=\"#myModal2\">회원가입</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            }
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Modal 로그인 -->\r\n");
      out.write("            <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("               <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("                  <!-- Modal content-->\r\n");
      out.write("                  <div class=\"modal-content\">\r\n");
      out.write("                     <div class=\"modal-header\" style=\"padding: 50px 50px;\">\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\r\n");
      out.write("                        <h2 align=\"center\">로그인</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"modal-body\" style=\"padding: 40px 50px;\">\r\n");
      out.write("                        <form class=\"form-horizontal\" id=\"loginfrm\" method=\"post\">\r\n");
      out.write("                           <div class=\"form-group\" style=\"width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("                              <br> <br> <input type=\"text\" name=\"user_id\"\r\n");
      out.write("                                 placeholder=\"ID\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                                 style=\"width: 300px; background-color: #fafafa\"\r\n");
      out.write("                                 value=\"");
      out.print(saveid != null ? saveok : "");
      out.write("\"> <br>\r\n");
      out.write("                              <br> <input type=\"password\" name=\"user_pw\"\r\n");
      out.write("                                 placeholder=\"PASSWORD\" class=\"form-control\"\r\n");
      out.write("                                 required=\"required\"\r\n");
      out.write("                                 style=\"width: 300px; background-color: #fafafa\"> <br>\r\n");
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                                    <div class=\"checkbox\">\r\n");
      out.write("                                       <label> <input type=\"checkbox\" name=\"saveid\"\r\n");
      out.write("                                          class=\"text-align:center;\"\r\n");
      out.write("                                          ");
      out.print(saveid != null ? "checked" : "");
      out.write("> 아이디저장\r\n");
      out.write("                                       </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                               \r\n");
      out.write("\r\n");
      out.write("                              <div class=\"form-group\" style=\"margin-top:50px;\">\r\n");
      out.write("                                 <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-default\" id=\"login\"\r\n");
      out.write("                                       style=\"width: 180px;\">로그인</button>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div style=\"text-align: center;\">\r\n");
      out.write("                                 <a href=\"index.jsp?main=login/login_findid.jsp\" style=\"color: black;\">아이디ㆍ비밀번호 찾기</a>\r\n");
      out.write("                                \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                     </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Modal 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Modal 회원가입-->\r\n");
      out.write("            <div class=\"modal fade\" name=\"myModal2\" id=\"myModal2\" role=\"dialog\">\r\n");
      out.write("               <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("                  <!-- Modal content-->\r\n");
      out.write("                  <div class=\"modal-content\">\r\n");
      out.write("                     <div class=\"modal-header\" style=\"padding: 35px 50px;\">\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\r\n");
      out.write("                        <h2 align=\"center\">회원가입</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"modal-body\" style=\"padding: 40px 50px;\">\r\n");
      out.write("                        <form class=\"form-horizontal\" method=\"post\" id=\"gaipfrm\">\r\n");
      out.write("                           <div class=\"form-group\" style=\"width: 300px;\">\r\n");
      out.write("\r\n");
      out.write("                              <br> <br> <input type=\"text\" name=\"user_name\"\r\n");
      out.write("                                 placeholder=\"이름\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                                 style=\"width: 300px; background-color: #fafafa\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                              <br> <br> <input type=\"text\" name=\"user_nickname\"\r\n");
      out.write("                                 placeholder=\"닉네임\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                                 style=\"width: 300px; background-color: #fafafa\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                              <br> <br> <input type=\"text\" name=\"user_id\"\r\n");
      out.write("                                 id=\"user_id\" placeholder=\"아이디\" class=\"form-control\"\r\n");
      out.write("                                 required=\"required\"\r\n");
      out.write("                                 style=\"width: 70%; background-color: #fafafa\">\r\n");
      out.write("\r\n");
      out.write("                              <button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("                                 style=\"margin-top: -55px; margin-left: 220px;\" id=\"id_check\">중복확인</button>\r\n");
      out.write("\r\n");
      out.write("                              <div id=\"check_result\"></div>\r\n");
      out.write("\r\n");
      out.write("                              <br> <br> <input type=\"password\" name=\"user_pw\"\r\n");
      out.write("                                 id=\"user_pw1\" placeholder=\"비밀번호\" class=\"form-control\"\r\n");
      out.write("                                 required=\"required\"\r\n");
      out.write("                                 style=\"width: 300px; background-color: #fafafa\"> <br>\r\n");
      out.write("                              <br> <input type=\"password\" name=\"user_pw2\" id=\"user_pw2\"\r\n");
      out.write("                                 placeholder=\"비밀번호확인\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                                 style=\"width: 300px; background-color: #fafafa\">\r\n");
      out.write("                              <div id=\"pw_check\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                              <br> <br> <input type=\"text\" name=\"user_hp\"\r\n");
      out.write("                                 placeholder=\"휴대번호\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                                 style=\"width: 300px; background-color: #fafafa\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("                              <br> <br> <input type=\"text\" name=\"user_addr\"\r\n");
      out.write("                                 placeholder=\"주소\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                                 style=\"width: 300px; background-color: #fafafa\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("                              <br> <br> <input type=\"text\" name=\"user_email\"\r\n");
      out.write("                                 placeholder=\"이메일\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                                 style=\"width: 300px; background-color: #fafafa\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("                              <br> <br>\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-default\"\r\n");
      out.write("                                       style=\"width: 180px;\" id=\"gaip\">회원가입</button>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                     </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Modal2 끝 -->\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
