/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-21 00:38:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.dto.MovieDto;
import java.util.List;
import data.dao.MovieDao;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("data.dao.MovieDao");
    _jspx_imports_classes.add("data.dto.MovieDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<title>main</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;700&family=Noto+Sans:wght@400;700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/main.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/slidebtn.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"script/script.js\" defer type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/7027f21a5f.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://use.fontawesome.com/releases/v5.2.0/css/all.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("	");

	MovieDao dao=new MovieDao();
	List<MovieDto> list_rank = dao.getList_Rank_Avg(0,5);
	List<MovieDto> list_pick1 = dao.getList_Pcount(0, 4);
	List<MovieDto> list_pick2 = dao.getList_Pcount(4, 4);
	List<MovieDto> list_pick3 = dao.getList_Pcount(8, 4);
	List<MovieDto> list_pick4 = dao.getList_Pcount(12, 4);
	List<MovieDto> list_pick5 = dao.getList_Pcount(16, 4);
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"bodywrap\">\r\n");
      out.write("		<div class=\"imgslide\">\r\n");
      out.write("			<a href=\"#\"><img alt=\"\" src=\"layout_image/1.png\"></a> <a\r\n");
      out.write("				href=\"#\"><img alt=\"\" src=\"layout_image/2.png\"></a> <a href=\"#\"><img\r\n");
      out.write("				alt=\"\" src=\"layout_image/3.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div>\r\n");
      out.write("			<div id=\"moviewrap\">\r\n");
      out.write("				<main class=\"main\">\r\n");
      out.write("					<section id=\"upcoming\">\r\n");
      out.write("						<h2 style=\"text-align: center; color: #A0298E; font-weight: bold;\">평점\r\n");
      out.write("							TOP5</h2>\r\n");
      out.write("						<div class=\"pickimg_item\" style=\"padding: 20px;\">\r\n");
      out.write("							<ul class=\"top5_list\">\r\n");
      out.write("								<!-- 5개만 넣기..! -->							\r\n");
      out.write("								");

									for(MovieDto dto:list_rank){
      out.write("\r\n");
      out.write("										\r\n");
      out.write("										<li>\r\n");
      out.write("											<a href=\"index.jsp?main=review/review_moviedetail.jsp?movie_genre=all&sort=recent&movie_num=");
      out.print(dto.getMovie_num());
      out.write("&currentPage=1\">\r\n");
      out.write("												<img src=\"movie_save/");
      out.print(dto.getMovie_poster());
      out.write("\">\r\n");
      out.write("											</a>\r\n");
      out.write("											<h3 class=\"img_text\" style=\"font-size:20px;\">");
      out.print(dto.getMovie_subject());
      out.write(" <b style=\"color:yellow; font-size:23px;\">★</b>");
      out.print(Math.round(dto.getMovie_rank_avg()*10.0)/10.0 );
      out.write(" </h3>\r\n");
      out.write("										</li>\r\n");
      out.write("									");
}
								
      out.write("\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("				</main>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("			<div class=\"slide_wrap\">\r\n");
      out.write("				<div class=\"slide_box\">\r\n");
      out.write("					<h2\r\n");
      out.write("						style=\"text-align: center; color: #653491; font-weight: bold; margin-bottom: 40px;\">BEST\r\n");
      out.write("						PICK</h2>\r\n");
      out.write("					<div class=\"slide_list clearfix\">\r\n");
      out.write("						<div class=\"slide_content slide01\" style=\"padding-left: 40px;\">\r\n");
      out.write("							<main class=\"slide_main2\">\r\n");
      out.write("								<section id=\"upcoming2\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										");

										for(MovieDto dto:list_pick1){
      out.write("\r\n");
      out.write("										\r\n");
      out.write("											<li>\r\n");
      out.write("												<a href=\"index.jsp?main=review/review_moviedetail.jsp?movie_genre=all&sort=recent&movie_num=");
      out.print(dto.getMovie_num());
      out.write("&currentPage=1\">\r\n");
      out.write("													<img src=\"movie_save/");
      out.print(dto.getMovie_poster());
      out.write("\">\r\n");
      out.write("												</a>\r\n");
      out.write("												<h3 class=\"img_text\">");
      out.print(dto.getMovie_pcount() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(dto.getMovie_subject());
      out.write("</h3>\r\n");
      out.write("											</li>\r\n");
      out.write("										");
}
      out.write("\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section>\r\n");
      out.write("							</main>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"slide_content slide02\" style=\"padding-left: 40px;\">\r\n");
      out.write("							<main class=\"slide_main2\">\r\n");
      out.write("								<section id=\"upcoming2\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										");

										for(MovieDto dto:list_pick2){
      out.write("\r\n");
      out.write("										\r\n");
      out.write("											<li>\r\n");
      out.write("												<a href=\"index.jsp?main=review/review_moviedetail.jsp?movie_genre=all&sort=recent&movie_num=");
      out.print(dto.getMovie_num());
      out.write("&currentPage=1\">\r\n");
      out.write("													<img src=\"movie_save/");
      out.print(dto.getMovie_poster());
      out.write("\">\r\n");
      out.write("												</a>\r\n");
      out.write("												<h3 class=\"img_text\">");
      out.print(dto.getMovie_pcount() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(dto.getMovie_subject());
      out.write("</h3>\r\n");
      out.write("											</li>\r\n");
      out.write("										");
}
      out.write("\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section>\r\n");
      out.write("							</main>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"slide_content slide03\" style=\"padding-left: 40px;\">\r\n");
      out.write("							<main class=\"slide_main2\">\r\n");
      out.write("								<section id=\"upcoming2\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										");

										for(MovieDto dto:list_pick3){
      out.write("\r\n");
      out.write("										\r\n");
      out.write("											<li>\r\n");
      out.write("												<a href=\"index.jsp?main=review/review_moviedetail.jsp?movie_genre=all&sort=recent&movie_num=");
      out.print(dto.getMovie_num());
      out.write("&currentPage=1\">\r\n");
      out.write("													<img src=\"movie_save/");
      out.print(dto.getMovie_poster());
      out.write("\">\r\n");
      out.write("												</a>\r\n");
      out.write("												<h3 class=\"img_text\">");
      out.print(dto.getMovie_pcount() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(dto.getMovie_subject());
      out.write("</h3>\r\n");
      out.write("											</li>\r\n");
      out.write("										");
}
      out.write("\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section>\r\n");
      out.write("							</main>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"slide_content slide04\" style=\"padding-left: 40px;\">\r\n");
      out.write("							<main class=\"slide_main2\">\r\n");
      out.write("								<section id=\"upcoming2\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										");

										for(MovieDto dto:list_pick4){
      out.write("\r\n");
      out.write("										\r\n");
      out.write("											<li>\r\n");
      out.write("												<a href=\"index.jsp?main=review/review_moviedetail.jsp?movie_genre=all&sort=recent&movie_num=");
      out.print(dto.getMovie_num());
      out.write("&currentPage=1\">\r\n");
      out.write("													<img src=\"movie_save/");
      out.print(dto.getMovie_poster());
      out.write("\">\r\n");
      out.write("												</a>\r\n");
      out.write("												<h3 class=\"img_text\">");
      out.print(dto.getMovie_pcount() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(dto.getMovie_subject());
      out.write("</h3>\r\n");
      out.write("											</li>\r\n");
      out.write("										");
}
      out.write("\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section>\r\n");
      out.write("							</main>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"slide_content slide05\" style=\"padding-left: 40px;\">\r\n");
      out.write("							<main class=\"slide_main2\">\r\n");
      out.write("								<section id=\"upcoming2\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										");

										for(MovieDto dto:list_pick5){
      out.write("\r\n");
      out.write("										\r\n");
      out.write("											<li>\r\n");
      out.write("												<a href=\"index.jsp?main=review/review_moviedetail.jsp?movie_genre=all&sort=recent&movie_num=");
      out.print(dto.getMovie_num());
      out.write("&currentPage=1\">\r\n");
      out.write("													<img src=\"movie_save/");
      out.print(dto.getMovie_poster());
      out.write("\">\r\n");
      out.write("												</a>\r\n");
      out.write("												<h3 class=\"img_text\">");
      out.print(dto.getMovie_pcount() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(dto.getMovie_subject());
      out.write("</h3>\r\n");
      out.write("											</li>\r\n");
      out.write("										");
}
      out.write("\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section>\r\n");
      out.write("							</main>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- // .slide_list -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- // .slide_box  <i class=\"fa-solid fa-chevron-right\"></i>-->\r\n");
      out.write("				<div class=\"slide_btn_box\">\r\n");
      out.write("					<button type=\"button\" class=\"slide_btn_prev fa-solid fa-circle-chevron-left\"></button>\r\n");
      out.write("					<button type=\"button\" class=\"slide_btn_next fa-solid fa-circle-chevron-right\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- // .slide_btn_box -->\r\n");
      out.write("				<ul class=\"slide_pagination\"></ul>\r\n");
      out.write("				<!-- // .slide_pagination -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- // .slide_wrap -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- // .container -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
