/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-20 05:27:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.movie;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.dto.MovieDto;
import data.dao.MovieDao;

public final class movie_005fupdateform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.dao.MovieDao");
    _jspx_imports_classes.add("data.dto.MovieDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>WPICK</title>\r\n");
      out.write("<link rel=\"favicon\" href=\"../layout_image/titlelogo.ico\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"../layoutimage/x-icon\" href=\"../layout_image/titlelogo.ico\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;700&family=Noto+Sans:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/movie.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("      $(function(){\r\n");
      out.write("         $(\"span.camera\").click(function(){\r\n");
      out.write("            $(\"#movie_poster\").trigger(\"click\"); //이벤트 강제호출 : trigger\r\n");
      out.write("         });\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      //이미지미리보기\r\n");
      out.write("      function readURL(input) {\r\n");
      out.write("           if (input.files && input.files[0]) {\r\n");
      out.write("               var reader = new FileReader(); \r\n");
      out.write("               reader.onload = function (e) {\r\n");
      out.write("                   $('#showimg').attr('src', e.target.result);\r\n");
      out.write("               }                   \r\n");
      out.write("               reader.readAsDataURL(input.files[0]);\r\n");
      out.write("           }\r\n");
      out.write("       }\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   list-style: none;\r\n");
      out.write("   font-family:\"Noto Sans KR\";\r\n");
      out.write("   color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mv_subject {\r\n");
      out.write("   font-size: 33px;\r\n");
      out.write("   font-weight: 700;\r\n");
      out.write("   letter-spacing: -1.2px;\r\n");
      out.write("   line-height: 41px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mv_content {\r\n");
      out.write("   font-size: 17px;\r\n");
      out.write("   font-weight: 400;\r\n");
      out.write("   letter-spacing: -0.7px;\r\n");
      out.write("   line-height: 22px;\r\n");
      out.write("   margin-top: 4px;\r\n");
      out.write("   margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("margin-bottom: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

	String movie_num=request.getParameter("movie_num");
	
	
	MovieDao dao=new MovieDao();
	MovieDto dto=dao.getData(movie_num);

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div style=\"margin-top: 100px; padding: 0; margin-bottom:300px;\">\r\n");
      out.write("      <form action=\"movie/movie_updateaction.jsp\" method=\"post\"\r\n");
      out.write("         enctype=\"multipart/form-data\">\r\n");
      out.write("         <input type=\"hidden\" name=\"movie_num\" value=\"");
      out.print(movie_num);
      out.write("\">\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <table style=\"width: 1000px;\">\r\n");
      out.write("            <caption>\r\n");
      out.write("               <b class=\"mv_content\">영화포스터</b> <span\r\n");
      out.write("                  class=\"glyphicon glyphicon-camera camera\"></span> <input\r\n");
      out.write("                  type=\"file\" name=\"movie_poster\" id=\"movie_poster\" \r\n");
      out.write("                  style=\"visibility: hidden;\" onchange=\"readURL(this)\">\r\n");
      out.write("            </caption>\r\n");
      out.write("            <tr height=\"100\">\r\n");
      out.write("               <td rowspan=\"4\" width=\"200\">\r\n");
      out.write("                  <!-- 이미지 미리보기 할 위치 --> <img id=\"showimg\" src=\"movie_save/");
      out.print(dto.getMovie_poster());
      out.write("\"\r\n");
      out.write("                  style=\"max-width: 200px;\">\r\n");
      out.write("               </td>\r\n");
      out.write("               <td width=\"200\"><b class=\"mv_subject\">영화 제목</b></td>\r\n");
      out.write("               <td width=\"400\"><input type=\"text\" name=\"movie_subject\" required=\"required\"\r\n");
      out.write("                  id=\"movie_subject\" class=\"form-control\" value=\"");
      out.print(dto.getMovie_subject());
      out.write("\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td><b class=\"mv_content\">개봉연도</b></td>\r\n");
      out.write("\r\n");
      out.write("               <td><input type=\"date\" name=\"movie_year\" id=\"movie_year\" required=\"required\"\r\n");
      out.write("                  class=\"form-control\" style=\"width: 200px;\" value=\"");
      out.print(dto.getMovie_year());
      out.write("\">\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td><b class=\"mv_content\">영화장르</b></td>\r\n");
      out.write("\r\n");
      out.write("               <td><select name=\"movie_genre\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                  style=\"width: 200px;\">\r\n");
      out.write("                     <option value=\"romance\">로맨스</option>\r\n");
      out.write("                     <option value=\"action\">액션</option>\r\n");
      out.write("                     <option value=\"comedy\">코미디</option>\r\n");
      out.write("                     <option value=\"horror\">공포</option>\r\n");
      out.write("                     <option value=\"animation\">애니메이션</option>\r\n");
      out.write("                     <option value=\"etc\">기타</option>\r\n");
      out.write("               </select></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td><b class=\"mv_content\">국가</b></td>\r\n");
      out.write("\r\n");
      out.write("               <td><input type=\"text\" name=\"movie_nara\" id=\"movie_nara\" required=\"required\"\r\n");
      out.write("                  class=\"form-control\" style=\"width: 200px;\"value=\"");
      out.print(dto.getMovie_nara());
      out.write("\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"write\" style=\"align: center; margin-left: 500px;\">\r\n");
      out.write("            <h3>줄거리</h3>\r\n");
      out.write("            <br>\r\n");
      out.write("            <textarea style=\"width: 1000px; height: 400px;\" name=\"movie_content\" required=\"required\"\r\n");
      out.write("               id=\"movie_comtent\">");
      out.print(dto.getMovie_content());
      out.write("</textarea>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div\r\n");
      out.write("            style=\"margin-left:500px; width: 1000px; height: 100px; padding: 0;\">\r\n");
      out.write("            <h3>출연/제작</h3>\r\n");
      out.write("            <div style=\"height: 100px; padding-left: 100px;\">\r\n");
      out.write("               <b class=\"mv_content\">감독</b> <br> <input type=\"text\"\r\n");
      out.write("                  name=\"movie_director\" id=\"movie_director\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                  style=\"width: 300px;\" value=\"");
      out.print(dto.getMovie_director());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"height: 100px; padding-left: 100px;\">\r\n");
      out.write("               <b class=\"mv_content\">출연진</b> <br> <input type=\"text\"\r\n");
      out.write("                  name=\"movie_actor\" id=\"movie_actor\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                  style=\"width: 300px;\" value=\"");
      out.print(dto.getMovie_actor());
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("               <div style=\"height: 100px; padding-left: 100px;\">\r\n");
      out.write("                  <b class=\"mv_content\">유튜브 트레일러(링크)</b> <input type=\"text\"\r\n");
      out.write("                     name=\"movie_play\" id=\"movie_play\" class=\"form-control\" required=\"required\"\r\n");
      out.write("                     style=\"width: 700px;\" value=\"");
      out.print(dto.getMovie_play());
      out.write("\">\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("               <button type=\"submit\" class=\"btn btn-default btn-ls\"\r\n");
      out.write("                  style=\"float: right; margin-right: 500px;\">영화수정</button>\r\n");
      out.write("            \r\n");
      out.write("         </div>\r\n");
      out.write("        </form>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
